---
title: "R Notebook"
output: html_notebook
---

## List of environments

```{r}
library(reticulate)
reticulate::conda_list()
```

## Linux + Anaconda2 root

```{r}
# Linux
# Use this in a Linux installation
reticulate::use_condaenv("anaconda2")
reticulate::py_config()
```

```{python}
# Linux + Anaconda2 as default
# this variable is important so RStudio doesn't crash
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '/home/superuser/anaconda2/plugins/platforms'
```

## Windows + Anaconda3 root

```{r}
# Windows
# this is the physical machine installation
reticulate::use_condaenv("anaconda3")
reticulate::py_config()
```

```{python}
# Windows
# this is the physical machine installation
# this variable is important so RStudio doesn't crash
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/msfz751/Anaconda3/Library/plugins/platforms'
```

## Windows + environment `pytorch37`

```{r}
# Windows
reticulate::use_condaenv("pytorch37")
reticulate::py_config()
```

```{python}
# Windows
# this variable is important so RStudio doesn't crash
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/msfz751/Anaconda3/envs/pytorch37/Library/plugins/platforms'
```


## Tensorflow 

```{r}
reticulate::use_condaenv("tensorflow")
```


```{r}
library(reticulate)

reticulate::use_condaenv("r-tensorflow")
reticulate::py_config()

library(tensorflow)
```

## PyTorch 

```{r}
library(reticulate)

reticulate::use_condaenv("pytorch")

torch <- import("torch")
np <- import("numpy", convert=FALSE)

torch$Tensor(5L, 4L)
```




```{r}
reticulate::use_python("C:\\Users\\msfz751\\Anaconda2\\envs\\docker\\python.exe")
reticulate::py_config()
reticulate::py_available()
```

```{r}
reticulate::py_available()
```

```{r}
reticulate::py_discover_config(use_environment = "r-35")
```


```{r}
reticulate::py_available(initialize = TRUE)
```


```




