---
title: "Sharing variables between Python and R"
output: html_notebook
---

## Linux + Anaconda2 root

```{r}
# Use this in a Linux installation
reticulate::use_condaenv("anaconda2")
reticulate::py_config()
```

```{python}
# Linux
# this variable is important so RStudio doesn't crash
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '/home/superuser/anaconda2/plugins/platforms'
```


## Windows + environment `pytorch`

```{r}
# Windows
reticulate::use_condaenv("pytorch37")
reticulate::py_config()
```

```{python}
# Windows
# this variable is important so RStudio doesn't crash
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/msfz751/Anaconda3/envs/pytorch37/Library/plugins/platforms'
```



```{python}
import pandas

flights = pandas.read_csv("flights.csv")
flights = flights[flights["DESTINATION_AIRPORT"] == "ORD"]
flights = flights[["AIRLINE", "DEPARTURE_DELAY", "ARRIVAL_DELAY"]]
flights = flights.dropna()
print(flights.head())
```

```{python}
# this crashes in Linux with RStudio 1.2.1114 without specifying plugin path environment
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2*np.pi*t)
plt.plot(t, s)
plt.show()
```

