---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

A quick tester of an environment variable working for PyQt.

```{r}
# Windows
# this is the physical machine installation
reticulate::use_condaenv("anaconda3")
reticulate::py_config()
```

```{r}
reticulate::use_condaenv("pytorch37")
reticulate::py_config()
```

```{r}
# Use this in a Linux installation
library(reticulate)
reticulate::use_condaenv("anaconda2")
reticulate::py_config()
```

```{python}
# Linux
# this variable is important so RStudio doesn't crash
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '/home/superuser/anaconda2/plugins/platforms'
```


```{python}
# Windows
# this variable is important so RStudio doesn't crash
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/msfz751/Anaconda3/envs/pytorch37/Library/plugins/platforms'
```

```{python}
# Windows
# this is the physical machine installation
# this variable is important so RStudio doesn't crash
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/msfz751/Anaconda3/Library/plugins/platforms'
```

```{python}
# this chunk with matplotlib will only run if the PyQt plugin path has been specified
import matplotlib
import matplotlib.pyplot as plt
import numpy as np


t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

plt.show()
```

