---
title: "R Notebook"
output: html_notebook
---

```{r}
library(reticulate)

a <- array(c(1:24), dim = c(2,3,4))

py_a <- r_to_py(a)

r_a <- py_to_r(py_a)

identical(a, r_a)

py_a$flags
```



Another example which illustrates that NumPy receives the 3d array correctly:
```{r}
library(reticulate)

a <- array(c(1:24), dim = c(2,3,4))

py_a <- r_to_py(a)

py_a$shape
# [[1]]
# [1] 2
# 
# [[2]]
# [1] 3
# 
# [[3]]
# [1] 4


py_a$flatten(order = 'F')
 # [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

r_a <- py_to_r(py_a)

identical(a, r_a)
# [1] TRUE

py_a$flags
```


```{r}
library(reticulate)
np <- import("numpy")
a <- array(c(1:24), dim = c(2,3,4))
pf <- r_to_py(a)
pc <- py_run_string("import numpy; a = numpy.arange(1,25).reshape(2,3,4)")
pc <- py_get_attr(pc, "a")

o <- import("operator")
o$sub(pf, pc)
#, , 1
#
#     [,1] [,2] [,3]
#[1,]    0   -2   -4
#[2,]  -11  -13  -15

# ...  (should all be zero)
```

```{r}
library(reticulate)
np <- import("numpy")
pf <- py_run_string("import numpy; a = numpy.reshape(numpy.arange(1,25), (2,3,4), 'F')")
pf <- py_get_attr(pf, "a")
pc <- py_run_string("import numpy; b = numpy.arange(1,25).reshape(2,3,4)")
pc <- py_get_attr(pc, "b")

o <- import("operator")
o$sub(pf, pc)
#, , 1
#
#     [,1] [,2] [,3]
#[1,]    0   -2   -4
#[2,]  -11  -13  -15   # ...  (not all zero)
```

```{r}
library(reticulate)
np <- import("numpy")
# 2-d
a <- py_run_string("import numpy; a = numpy.arange(1, 5).reshape(2, 2)")
a
# a <- py_get_attr(a, '$a')
(a_a <- a$a)

# 3-d not consistent
b <- py_run_string("import numpy; b = numpy.arange(1, 9).reshape(2, 2, 2)")
# b <- py_get_attr(b, "b")
b <- b$b

a_a
# [[1 2]
# [3 4]]
# py_to_r(a)
#     [,1] [,2]
#[1,]    1    2
#[2,]    3    4

b_b
#[[[1 2]
#  [3 4]]
#
# [[5 6]
#  [7 8]]]
# py_to_r(b)
#, , 1
#     [,1] [,2]
#[1,]    1    3
#[2,]    5    7
#
#, , 2
#     [,1] [,2]
#[1,]    2    4
#[2,]    6    8
```

